# Generated by Django 5.1.7 on 2025-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('professor', 'Professor')], max_length=10),
        ),
    ]
