# Generated by Django 5.1.4 on 2025-03-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('student_count', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
