# Generated by Django 5.1.4 on 2025-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#9b59b6', max_length=7),
        ),
    ]
