# Generated by Django 5.1.4 on 2025-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default='#e67e22', max_length=7),
        ),
    ]
