# Generated by Django 5.1.7 on 2025-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_courseform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
