# Generated by Django 5.1.7 on 2025-03-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_courseform_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseform',
            name='id',
        ),
        migrations.AddField(
            model_name='courseform',
            name='form_id',
            field=models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
