# Generated by Django 5.1.7 on 2025-03-31 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_courseform_id_courseform_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
    ]
