# Generated by Django 5.1.7 on 2025-03-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_courseform_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikertQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('label_1', models.CharField(max_length=255)),
                ('label_2', models.CharField(max_length=255)),
                ('label_3', models.CharField(max_length=255)),
                ('label_4', models.CharField(max_length=255)),
                ('label_5', models.CharField(max_length=255)),
                ('color_1', models.CharField(max_length=7)),
                ('color_2', models.CharField(max_length=7)),
                ('color_3', models.CharField(max_length=7)),
                ('color_4', models.CharField(max_length=7)),
                ('color_5', models.CharField(max_length=7)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likert_questions', to='dashboard.course')),
            ],
        ),
    ]
