# Generated by Django 5.1.7 on 2025-03-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_likertquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='name',
            field=models.CharField(default='Untitled form', max_length=255),
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('course_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='dashboard.courseform')),
            ],
        ),
    ]
