# Generated by Django 5.1.7 on 2025-03-31 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_courseform_name_openquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertquestion',
            name='course',
        ),
        migrations.AddField(
            model_name='likertquestion',
            name='course_form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likert_questions', to='dashboard.courseform'),
            preserve_default=False,
        ),
    ]
