# Generated by Django 5.1.7 on 2025-03-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_likertquestion_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openquestion',
            name='course_form',
        ),
        migrations.DeleteModel(
            name='LikertQuestion',
        ),
        migrations.DeleteModel(
            name='OpenQuestion',
        ),
    ]
