# Generated by Django 5.1.7 on 2025-03-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_team'),
        ('dashboard', '0014_remove_openquestion_course_form_and_more'),
    ]

    operations = [
    ]
