# Generated by Django 5.1.7 on 2025-04-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_merge_20250331_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='course',
        ),
        migrations.RemoveField(
            model_name='team',
            name='students',
        ),
        migrations.DeleteModel(
            name='CourseForm',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
