# Generated by Django 5.1.7 on 2025-04-02 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0016_remove_team_course_remove_team_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseForm',
            fields=[
                ('form_id', models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Untitled form', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('num_likert', models.PositiveIntegerField(default=3)),
                ('num_open', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('self_evaluate', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.course')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
