# Generated by Django 5.1.7 on 2025-04-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('dashboard', '0016_remove_team_course_remove_team_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseform',
            name='form_id',
        ),
        migrations.AddField(
            model_name='courseform',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseform',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='course_forms', to='course.team'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_forms', to='dashboard.course'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='name',
            field=models.CharField(default='Untitled Form', max_length=255),
        ),
    ]
