# Generated by Django 5.1.7 on 2025-04-07 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courseform_form_id_courseform_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.IntegerField()),
                ('option_1', models.CharField(max_length=255)),
                ('color_1', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('option_2', models.CharField(max_length=255)),
                ('color_2', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('option_3', models.CharField(max_length=255)),
                ('color_3', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('option_4', models.CharField(max_length=255)),
                ('color_4', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('option_5', models.CharField(max_length=255)),
                ('color_5', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('course_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likert_questions', to='course.courseform')),
            ],
        ),
        migrations.CreateModel(
            name='LikertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('likert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='course.likert')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='likert_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('order', models.IntegerField()),
                ('course_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_ended_questions', to='course.courseform')),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('open_ended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='course.openendedquestion')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='open_ended_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
