# Generated by Django 5.1.7 on 2025-04-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_likert_likertresponse_openendedquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseform',
            old_name='num_open',
            new_name='num_open_ended',
        ),
    ]
