# Generated by Django 5.1.7 on 2025-04-09 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_num_open_courseform_num_open_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likert',
            name='color_1',
        ),
        migrations.RemoveField(
            model_name='likert',
            name='color_2',
        ),
        migrations.RemoveField(
            model_name='likert',
            name='color_3',
        ),
        migrations.RemoveField(
            model_name='likert',
            name='color_4',
        ),
        migrations.RemoveField(
            model_name='likert',
            name='color_5',
        ),
        migrations.AddField(
            model_name='courseform',
            name='color_1',
            field=models.CharField(default=1234567, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseform',
            name='color_2',
            field=models.CharField(default=1234567, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseform',
            name='color_3',
            field=models.CharField(default=1234567, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseform',
            name='color_4',
            field=models.CharField(default=1234567, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseform',
            name='color_5',
            field=models.CharField(default=1234567, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
            preserve_default=False,
        ),
    ]
