# Generated by Django 5.1.7 on 2025-04-09 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_likert_color_1_remove_likert_color_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='color_1',
            field=models.CharField(default='#872729', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='color_2',
            field=models.CharField(default='#C44B4B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='color_3',
            field=models.CharField(default='#F2F0EF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='color_4',
            field=models.CharField(default='#3D5A80', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='color_5',
            field=models.CharField(default='#293241', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
