# Generated by Django 5.1.7 on 2025-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_courseform_color_1_alter_courseform_color_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseform',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('released', 'Released')], default='draft', max_length=8),
        ),
    ]
