# Generated by Django 5.1.7 on 2025-04-09 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_courseform_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
