# Generated by Django 5.1.7 on 2025-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_courseform_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('released', 'Released')], default='draft', max_length=9),
        ),
    ]
