# Generated by Django 5.1.7 on 2025-04-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_courseform_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenEndedQuestion',
            new_name='OpenEnded',
        ),
    ]
