<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-15 03:10
=======
# Generated by Django 5.1.7 on 2025-04-15 17:01
>>>>>>> 89949e61fbb149609bb041b4920e967dae3e2756

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_openendedquestion_openended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='openendedresponse',
            name='student',
        ),
        migrations.AddField(
            model_name='likertresponse',
            name='evaluator',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='likert_responses_as_evaluator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likertresponse',
            name='evaluee',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='likert_responses_as_evaluee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openendedresponse',
            name='evaluator',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='open_ended_responses_as_evaluator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openendedresponse',
            name='evaluee',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='open_ended_responses_as_evaluee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
