# Generated by Django 5.1.7 on 2025-04-27 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_likertresponse_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseform',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='courseform',
            name='due_time',
        ),
        migrations.AddField(
            model_name='courseform',
            name='due_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
